### ISSUE TITLE
Browser icons not loading

### ISSUE THREAD

**Issue by i0ntempest** [will-stone/browserosaurus#539]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

![Screen Shot 2022-05-28 at 23 47 59](https://user-images.githubusercontent.com/16017904/170851214-83632707-b7fa-4dba-afb6-4459e03eca58.png)

### Expected Behaviour

Icons should show up

### Steps To Reproduce

Upgrade to 18.2 and open picker window

### Browserosaurus version

18.2.0

### macOS version

12.4 and 12.5

### CPU Architecture

Intel

**Comment by will-stone** [comment]
Hmmm 🤔 Are you waiting for the scan to complete? It can take about 30 seconds on an intel machine (pretty much instantaneous on M1).

**Comment by LeoDoesThings** [comment]
I also have this problem. Tried reinstalling and waiting but still no icons showing in browser prompt or preferences.
MacOS 12.4, Browserosaurus v18.2.0, Intel Mac.
<img width="590" alt="image" src="https://user-images.githubusercontent.com/38830741/170855378-0b4cbfd9-94eb-4e7a-8b57-6db23c6b0333.png">
<img width="253" alt="image" src="https://user-images.githubusercontent.com/38830741/170855397-cab2cebb-fd3d-436c-afc1-ae25724a9a86.png">

**Comment by will-stone** [comment]
Does it work if you click the Factory Reset in the General preferences pane, and then restart the app?

**Comment by i0ntempest** [comment]
I did a reset and the wheel has been spinning for 5 minutes...

**Comment by i0ntempest** [comment]
10+ minutes and still nothing, pretty sure it's stuck.

**Comment by i0ntempest** [comment]
Ok this is weird, I checked out the code at v18.2 and run that with npm, the scan completes just fine.

**Comment by joel-tonuri** [comment]
Same issue here since updating.

**Comment by porcherie** [comment]
same problem here, MacBook Pro 2020 M1, macOS 12.4.
tried in installing app with app cleaner and reinstall fresh but all I get is the spinning wheel

**Comment by will-stone** [comment]
Hmmm, maybe it's because there's something in the [file-icon](https://github.com/sindresorhus/file-icon) package that's not being bundled with the app, but is globally on my system. That's just a hunch.

If the loading spinner just spins, it means that the main process has thrown an error, otherwise you'd get the list of installed browsers just not the images. I'll put a try/catch around the [getAppIcon](https://github.com/will-stone/browserosaurus/blob/ea3d2e50163da049f69c733555134330fa79b083/src/main/utils/filter-apps-by-installed.ts#L17) call and see if it at least allows you to get the list of apps, even if you don't end up with the icons.

Then I think I need to look into bundling native node modules.

**Comment by will-stone** [comment]
This ☝️  may not be today, so I suggest downgrading to 18.1.0 for now.

**Comment by henocookie** [comment]
Just adding I've also had this bug on a M1 MacBook Pro 202
<img width="362" alt="Screenshot 2022-05-31 at 9 44 56 am" src="https://user-images.githubusercontent.com/52792328/171138749-9a6d9564-3e42-4cba-ac23-b9f1c70eddbd.png">
0

**Comment by will-stone** [comment]
I've got an intel mac for work, and can reproduce the bug. However, I also [setup support for native node modules](https://github.com/will-stone/browserosaurus/blob/aac97f544d7a6edc6885008d96698f7f2cac50f0/webpack.rules.cjs#L3) and packaged the app and sent it to my work mac, and it's still not producing the icons. The file-icon package uses Swift code, or a it might be a permissions thing, any help will be appreciated. I'll release the updated app soon, that will at least allow you to upgrade and not show the infinite spinner if you factory reset. But other than that, I'm not really sure how to debug this 😖 And I'd rather not go back to shipping the icons in the app.

**Comment by kiwi-x** [comment]
Hi. 

I just did an fresh install via Homebrew on my new m1 Mac. Browserosaurus didn't find any browser installed on my machine. After finding this thread I removed the latest version 18.2.0 and installed the 18.1.0 version from GitHub release assets and the installed browser where detected immediately.

For me it looks like the browser detection is broken with the new version 18.2.0.

**Comment by will-stone** [comment]
18.3.0 released. It (probably) won't fix the icons but it'll at least find the browsers. I've explained what I think the issue(s) may be above. If you'd like to help, please take a look at why you think [the icons-detection feature](https://github.com/will-stone/browserosaurus/blob/main/src/main/utils/get-app-icons.ts) isn't working on the packaged app. As noted above by @i0ntempest, it seems to work fine on local install.

**Comment by i0ntempest** [comment]
> setup support for native node modules

I did not do this, what I did was running the two command in your "Setting up for development" tutorial using MacPorts npm. Also I have parts of SIP disabled on my system. So I guess it's either npm/node installed by MP is somewhat special, or SIP has effects on this. I'd suggest you try disabling SIP first, if you can do that on your work computer.

**Comment by will-stone** [comment]
I’m pretty sure I don’t have any SIP disabled 🤔 Do you have a command we can run to check? I’m currently looking to see how I can get an Electron app to log out to Console.app. Once I’ve figured that out, I should be able to just add a logger inside the catch to see if we can garner more info. We could possibly log a ticket on the file-icon repo, but I’d rather not do that until we have more info. 

@kiwi-x you'd need to run B locally: I.e clone this repo, run npm install, and npm start. B won’t find npm packages if run from the downloaded version.

**Comment by i0ntempest** [comment]
> Do you have a command we can run to check

`csrutil status`

**Comment by benjamingwynn** [comment]
18.3.0 produces no icons for me on macOS 12.4. SIP is enabled on my machine. What are the disadvantages of bundling the icons with the application exactly? It seems like the least complicated and least likely to fail solution from an outsiders perspective.

![noicons](https://user-images.githubusercontent.com/1631422/171411909-ad7e07d9-dd37-4336-838b-c4f614478259.png)
![noicons-2](https://user-images.githubusercontent.com/1631422/171411917-595a33b4-56a5-4168-a9dc-2d101470a504.png)

**Comment by will-stone** [comment]
It's about maintenance. Icons change over time, if they're taken from the system then Browserosaurus doesn't require a release when one changes, or even if the user [wants to change them themselves](https://github.com/will-stone/browserosaurus/blob/923395a683af81b0f22b454f497d31303cabc2a8/src/main/utils/get-app-icons.ts#L14). Also it lowers the barrier to supporting a new browser in the project. And finally, it means the app ships less code/bytes.

Okay, please no more "me too" posts 😅 In fact, it'd now be more productive to hear from people that _can_ see the icons. If there's an Electron bod out there that can show me how to log to Console.app, we can add that in the [catch](https://github.com/will-stone/browserosaurus/blob/923395a683af81b0f22b454f497d31303cabc2a8/src/main/utils/get-app-icons.ts#L14) and see why it seems to be broken on everyone's system but the one I develop on.

**Comment by benjamingwynn** [comment]
If you're looking into production logging then using a dependency like [electron-log](https://www.npmjs.com/package/electron-log) could help (or at least drawing inspiration from it), you could ask users to just go to `~/Library/Logs/Browersaurus` for the stack trace. I would assume it's a file access problem, but it'd be neat to see the log to be more helpful.

I can't find a way to bring up the dev console or any log output on the production build, I'm happy to help where I can but I can't seem to find a log anywhere at the moment. I could build the project, but I'm kinda assuming the development version has icons working fine (which is why you can see them)

Your point about icon maintaince makes a lot of sense, but maybe internal icons could be used as a fallback, even if they were low resolution? Then if this process failed (for whatever reason) you could use the internal icons in the catch block. Of course this depends on the relative impact on filesize

> Okay, please no more "me too" posts

Sorry for the spam! I was hoping the images would come out a bit smaller 😨

**Comment by will-stone** [comment]
Nice, thanks 😊 Feel free to PR that and I’ll do a patch release to see if we can start getting some data from people (and my work machine). It certainly is a weird one.

**Comment by will-stone** [comment]
Thanks @benjamingwynn. I've released 18.4.0 (minor bump as I've moved the update notification into the picker, no more blue icon 🥳).

Okay, after you've opened the picker or pref window, the icon retrieval will be attempted. Then check `~/Library/Logs/Browserosaurus/main.log` and see what we get. Please post your results here, hopefully we can get to the bottom of this 🤞

**Comment by i0ntempest** [comment]
```
cat Library/Logs/Browserosaurus/main.log 
[2022-06-02 03:05:43.476] [info]  Getting icon from ID com.apple.SafariTechnologyPreview
[2022-06-02 03:05:43.479] [error] Error: spawn /Users/will/Documents/github/will-stone/browserosaurus/node_modules/file-icon/file-icon ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-06-02 03:05:43.482] [info]  Getting icon from ID com.apple.Safari
[2022-06-02 03:05:43.482] [error] Error: spawn /Users/will/Documents/github/will-stone/browserosaurus/node_modules/file-icon/file-icon ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-06-02 03:05:43.483] [info]  Getting icon from ID com.google.Chrome
[2022-06-02 03:05:43.484] [error] Error: spawn /Users/will/Documents/github/will-stone/browserosaurus/node_modules/file-icon/file-icon ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-06-02 03:05:43.484] [info]  Getting icon from ID com.google.Chrome.canary
[2022-06-02 03:05:43.485] [error] Error: spawn /Users/will/Documents/github/will-stone/browserosaurus/node_modules/file-icon/file-icon ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-06-02 03:05:43.485] [info]  Getting icon from ID org.torproject.torbrowser
[2022-06-02 03:05:43.486] [error] Error: spawn /Users/will/Documents/github/will-stone/browserosaurus/node_modules/file-icon/file-icon ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-06-02 03:05:43.487] [info]  Getting icon from ID us.zoom.xos
[2022-06-02 03:05:43.487] [error] Error: spawn /Users/will/Documents/github/will-stone/browserosaurus/node_modules/file-icon/file-icon ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-06-02 03:05:47.883] [info]  Getting icon from ID com.apple.SafariTechnologyPreview
[2022-06-02 03:05:47.884] [error] Error: spawn /Users/will/Documents/github/will-stone/browserosaurus/node_modules/file-icon/file-icon ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-06-02 03:05:47.885] [info]  Getting icon from ID com.apple.Safari
[2022-06-02 03:05:47.886] [error] Error: spawn /Users/will/Documents/github/will-stone/browserosaurus/node_modules/file-icon/file-icon ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-06-02 03:05:47.886] [info]  Getting icon from ID com.google.Chrome
[2022-06-02 03:05:47.887] [error] Error: spawn /Users/will/Documents/github/will-stone/browserosaurus/node_modules/file-icon/file-icon ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-06-02 03:05:47.887] [info]  Getting icon from ID com.google.Chrome.canary
[2022-06-02 03:05:47.888] [error] Error: spawn /Users/will/Documents/github/will-stone/browserosaurus/node_modules/file-icon/file-icon ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-06-02 03:05:47.888] [info]  Getting icon from ID org.torproject.torbrowser
[2022-06-02 03:05:47.889] [error] Error: spawn /Users/will/Documents/github/will-stone/browserosaurus/node_modules/file-icon/file-icon ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-06-02 03:05:47.889] [info]  Getting icon from ID us.zoom.xos
[2022-06-02 03:05:47.890] [error] Error: spawn /Users/will/Documents/github/will-stone/browserosaurus/node_modules/file-icon/file-icon ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by i0ntempest** [comment]
Yup, just as I thought. I symlinked file-icon binary to that hardcoded path and I now have icons.
```
cat Library/Logs/Browserosaurus/main.log 
[2022-06-02 03:17:54.784] [info]  Getting icon from ID com.apple.SafariTechnologyPreview
[2022-06-02 03:17:54.841] [info]  Getting icon from ID com.apple.Safari
[2022-06-02 03:17:54.903] [info]  Getting icon from ID com.google.Chrome
[2022-06-02 03:17:54.965] [info]  Getting icon from ID com.google.Chrome.canary
[2022-06-02 03:17:55.030] [info]  Getting icon from ID org.torproject.torbrowser
[2022-06-02 03:17:55.107] [info]  Getting icon from ID us.zoom.xos
```

**Comment by will-stone** [comment]
Oh wow, good spot! So that must be something happening at compile time. I wonder if I use the non-esm version of file-icon if that will work better with Electron.

https://github.com/sindresorhus/file-icon/blob/c4a1f7d3fb450694bb5eb4a9535e76a6696168c9/index.js#L8

vs

https://github.com/sindresorhus/file-icon/blob/bfe1b32b7341d881866aa6c57693dce6783dd70d/index.js#L8

I'll give it a go in the next release. If that fixes it, I can look into something like this: https://www.npmjs.com/package/@open-wc/webpack-import-meta-loader If anyone has experience with webpack 5 and `import.meta.url`, your knowledge could come in handy here 😊

**Comment by vitalii427** [comment]
Still same on 18.4.0  macOS 12.4 M1

**Comment by will-stone** [comment]
Well, so far I've tried the CJS version (v4) of file-icon, and get an `EACCES` error.

Keeping with the ESM version (v5) of file-icon but using the `importMeta: false` webpack config results in a `SyntaxError: Cannot use 'import.meta' outside a module` error.

So currently I'm a bit stumped 😕

**Comment by i0ntempest** [comment]
I don’t really know how electron/nodejs works, but if file-icons binary is bundled in the app, can’t you just use a relative path or use RPATH to reference the binary?

**Comment by will-stone** [comment]
Well, it's a third party package. I'll post an issue on their project when I get a chance, and see if they have any ideas on how to proceed. The maintainer, Sindre, used to be a keen Electron user, so hopefully he can help 🤞

**Comment by benjamingwynn** [comment]
You might need to build file-icons with webpack along with the project, so webpack can include the Switft binary in the output build files. To do this you may need to use a [loader](https://webpack.js.org/loaders/) to tell it how to include the binary properly, but it might be as simple as just adding `node_modules/file-icons/**` to the includes in the webpack config

**Comment by will-stone** [comment]
@benjamingwynn The file-icon Swift binary is wrapped in JS and so is included in my webpack build, it’s just `import.meta.url` that gets replaced at build time by an absolute file url, in this case my path to the module. However, a loader may be the right way to go but for replacing `import.meta.url` with a _relative_ path. Alternatively, I’m thinking I could build my own wrapper around the Swift binary.

**Comment by benjamingwynn** [comment]
Ah yeah, looking at file-icon's source I can see they use

`const __dirname = path.dirname(fileURLToPath(import.meta.url));`

So outside of webpack rewriting import.meta.url I'm unsure on if a specific loader would help, as the file isn't required/imported but rather loaded using `fs` (import.meta.url might actually be controlled by the loader too, again not sure)

The ideal option would be if you're just able to copy the binary into the output built application and tell Webpack `import.meta.url` should be .app/Contents/Resources (when NODE_ENV!='production'), but failing that maybe the `file-icon` team would be open for a pull request for loading the binary from a custom directory as a config option - seems better than either copying or reinventing their switft binary wrapper if they're up for it

**Comment by subfighter3** [comment]
Hi there, version 18.4 seemed to have fixed this issue, but after a while it's still there as 18.2..

**Comment by will-stone** [comment]
Here's my latest findings. I moved back to v4 of `file-icon` which is CJS, and will therefore not suffer from the `import.meta.url` issue, as that's an ESM-only thing. On first run, I get an `EACCES` (permissions) error.

A bit of background: when using native binaries, a package called [`@vercel/webpack-asset-relocator-loader`](https://github.com/vercel/webpack-asset-relocator-loader) moves the binary to `.webpack/main/native_modules/` so it can be seen by the webpack bundle.

So, this basically isn't copying the permissions of the file over with it. Which can be seen by running `npm start` and then manually copying the file from `node_modules/file-icon/file-icon` to `.webpack/main/native_modules/file-icon` before opening the picker or preferences window.

When I get a moment I'll put up a branch and draft PR with this in, and we can hopefully demo this to the `@vercel/webpack-asset-relocator-loader` project to see if there's anything we can do to fix it.

**Comment by will-stone** [comment]
Can somebody please clone and switch to the `#539-use-cjs-file-icon` branch, do an `npm install` followed by `npm start` and see if you get the same `EACCES` error when opening the picker or preferences windows? Thanks 😊

**Comment by i0ntempest** [comment]
I get `EACCESS` when I open Apps panel of B preferences, I guess it's the same thing:
```
19:59:33.329 › Getting icon from ID com.apple.SafariTechnologyPreview
19:59:33.335 › Error: spawn /Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[getAppIcon error] Error: spawn /Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon',
  path: '/Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon',
  spawnargs: [ '[{"appOrPID":"com.apple.SafariTechnologyPreview","size":64}]' ],
  cmd: '/Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon [{"appOrPID":"com.apple.SafariTechnologyPreview","size":64}]',
  stdout: <Buffer >,
  stderr: <Buffer >
}
19:59:33.339 › Getting icon from ID com.apple.Safari
19:59:33.341 › Error: spawn /Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[getAppIcon error] Error: spawn /Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon',
  path: '/Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon',
  spawnargs: [ '[{"appOrPID":"com.apple.Safari","size":64}]' ],
  cmd: '/Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon [{"appOrPID":"com.apple.Safari","size":64}]',
  stdout: <Buffer >,
  stderr: <Buffer >
}
19:59:33.342 › Getting icon from ID com.google.Chrome
19:59:33.343 › Error: spawn /Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[getAppIcon error] Error: spawn /Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon',
  path: '/Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon',
  spawnargs: [ '[{"appOrPID":"com.google.Chrome","size":64}]' ],
  cmd: '/Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon [{"appOrPID":"com.google.Chrome","size":64}]',
  stdout: <Buffer >,
  stderr: <Buffer >
}
19:59:33.344 › Getting icon from ID com.google.Chrome.canary
19:59:33.346 › Error: spawn /Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[getAppIcon error] Error: spawn /Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon',
  path: '/Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon',
  spawnargs: [ '[{"appOrPID":"com.google.Chrome.canary","size":64}]' ],
  cmd: '/Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon [{"appOrPID":"com.google.Chrome.canary","size":64}]',
  stdout: <Buffer >,
  stderr: <Buffer >
}
19:59:33.348 › Getting icon from ID org.torproject.torbrowser
19:59:33.349 › Error: spawn /Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[getAppIcon error] Error: spawn /Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon',
  path: '/Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon',
  spawnargs: [ '[{"appOrPID":"org.torproject.torbrowser","size":64}]' ],
  cmd: '/Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon [{"appOrPID":"org.torproject.torbrowser","size":64}]',
  stdout: <Buffer >,
  stderr: <Buffer >
}
19:59:33.351 › Getting icon from ID us.zoom.xos
19:59:33.353 › Error: spawn /Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[getAppIcon error] Error: spawn /Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon',
  path: '/Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon',
  spawnargs: [ '[{"appOrPID":"us.zoom.xos","size":64}]' ],
  cmd: '/Users/Admin/Downloads/browserosaurus/.webpack/main/native_modules/file-icon [{"appOrPID":"us.zoom.xos","size":64}]',
  stdout: <Buffer >,
  stderr: <Buffer >
}
MAIN   main/app-icons/got
{
  "com.apple.SafariTechnologyPreview": "",
  "com.apple.Safari": "",
  "com.google.Chrome": "",
  "com.google.Chrome.canary": "",
  "org.torproject.torbrowser": "",
  "us.zoom.xos": ""
}
PREFS  prefs/tab-button/clicked
"apps"
```

**Comment by will-stone** [comment]
Yeah that’s the one 👍 Okay, so it’s not just me.

**Comment by will-stone** [comment]
Have [asked Sindre for help](https://github.com/sindresorhus/file-icon/issues/13). Hopefully someone knows how to handle the package in an Electron environment 🤞

**Comment by will-stone** [comment]
This has been fixed in 18.4.1 🥳 Please note that it may take some time for them show on first show of the picker, I'll be looking to speed this up in future releases. The reason is takes so long is because the app currently takes the following journey:

- App loads.
- Browsers are not scanned for at this point, previously saved browsers are shown, without logos.
- User clicks link or opens the picker or prefs windows.
- App scans for browsers.
- App gets logos for all browsers returned by scan.

Hopefully, I can asynchronise the browser and logo scanning to speed it all up 🤞

**Comment by i0ntempest** [comment]
Looking good here! Thanks

**Comment by porcherie** [comment]
@will-stone you are right, working great here. Thanks for the effort, this one took long. Great job👍🏻
Love your app

**Comment by henocookie** [comment]
Working again, thanks for persisting! Super useful app 🤩

**Comment by jovobe** [comment]
I still have this bug on v18.4.2 (macOS 12.4 on MacBook with M1 Pro). I already reinstalled the app and reset to factory defaults. Are there any more actions I can try to resolve this?

**Comment by will-stone** [comment]
@jovobe Can you please clone and load the app locally (docs are on the readme) and see what the console says when it tries to load the icons? Thanks.

**Comment by nfekete** [comment]
Doesn't work for me either, v18.4.2.

This what I see in the logs (`~/Library/Logs/Browserosaurus/main.log`):
```
[2022-07-14 12:52:45.972] [error] Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:709:9)
    at execFile (node:child_process:336:17)
    at node:child_process:243:21
    at node:electron/js2c/asar_bundle:5:3313
    at mapper (/private/var/folders/9b/vfj_lcy17js151d83l4hqmj00000gn/T/AppTranslocation/8E9912D2-371A-4061-B292-BA2F332FA55A/d/Browserosaurus.app/Contents/Resources/app.asar/node_modules/file-icon/index.js:67:26)
    at /private/var/folders/9b/vfj_lcy17js151d83l4hqmj00000gn/T/AppTranslocation/8E9912D2-371A-4061-B292-BA2F332FA55A/d/Browserosaurus.app/Contents/Resources/app.asar/node_modules/p-map/index.js:57:28
```

**Comment by jovobe** [comment]
@will-stone sorry for the delayed answer. I finally found time to follow your instructions and I get the following error, when launching Browserosaurus:

<details>
<summary>See log here</summary>
```
No errors found.
MAIN   main/installed-apps/retrieved
[
  "com.google.Chrome",
  "net.kassett.finicky",
  "org.mozilla.firefox",
  "notion.id",
  "com.apple.Safari",
  "com.spotify.client",
  "us.zoom.xos"
]
21:30:20.954 › Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:709:9)
    at execFile (node:child_process:336:17)
    at node:child_process:243:21
    at node:electron/js2c/asar_bundle:5:3133
    at mapper (/Users/username/dev/browserosaurus/node_modules/file-icon/index.js:67:26)
    at /Users/username/dev/browserosaurus/node_modules/p-map/index.js:57:28
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[getAppIcon error] Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:709:9)
    at execFile (node:child_process:336:17)
    at node:child_process:243:21
    at node:electron/js2c/asar_bundle:5:3133
    at mapper (/Users/username/dev/browserosaurus/node_modules/file-icon/index.js:67:26)
    at /Users/username/dev/browserosaurus/node_modules/p-map/index.js:57:28
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
```
</details>

**Comment by will-stone** [comment]
@nfekete @jovobe To confirm, are you both definitely using the correct copy of Browserosaurus for your CPU architecture?

**Comment by nfekete** [comment]
@will-stone I installed Browserosaurus with `brew`, so I am not sure. How to check?

**Comment by nfekete** [comment]
Hmm, I tried with a manually downloaded version and it works now.

Is this how it supposed to look like? I am asking because the last version I've seen was 15.0.6, which looked quite differently from this.
<img width="263" alt="image" src="https://user-images.githubusercontent.com/16191714/180246792-b5c458e1-c173-480c-8540-fa0f1e7debf2.png">

I have also reinstalled the app with brew and I can confirm that it's installing the correct arm64 version.

**Comment by benjamingwynn** [comment]
Working great on my machine - thanks @will-stone!

**Comment by jovobe** [comment]
@will-stone I double-checked it, and I am using the correct version. I also tried the new released version v19.0.0 for ARM (darwin-arm64-19.0.0.zip) but I still get no icons: 
![grafik](https://user-images.githubusercontent.com/1265894/181219973-8c59180b-a53d-4f8c-8699-2c348b9dd3a2.png)

**Comment by will-stone** [comment]
I'm getting this on my new mac 😖 `Error: spawn Unknown system error -86` 🤷‍♂️

**Comment by will-stone** [comment]
Got it! You need to install Rosetta:
```
softwareupdate --install-rosetta
```
This is irritating because it's an arm binary and shouldn't need Rosetta. More digging required...

**Comment by will-stone** [comment]
Okay figured it out. I’m using v4 of file-icon but Apple silicon support wasn’t introduced until v5.1. Unfortunately it is hard to upgrade because v5+ is ESM only which Electron cannot use. I may have to fork the project or see if there’s an electron-transpile tool somewhere that can convert it to CommonJS.

**Comment by benjamingwynn** [comment]
can you use the old commonjs version with the new binary?

**Comment by will-stone** [comment]
Yeah, I’m currently looking at moving the binary directly into the project and writing my own wrapper around it.

**Comment by will-stone** [comment]
This will hopefully be fixed in the next release. I'll ping those effected when it's ready.

**Comment by will-stone** [comment]
@nfekete @jovobe Okay 19.0.1 is now available to download, restart B and go to prefs to see the update download button (I plan to improve this UX at some point).

**Comment by jovobe** [comment]
@will-stone thank you so much for fixing and pinging me! This seems to be a small thing, but you made my everyday work experience so much better 🎉 Going to get you a coffee right now ☕

**Comment by will-stone** [comment]
Ah, that’s much appreciated @jovobe 😊
